apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data-0
  namespace: monitoring
  labels:
    nfs: prometheus-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: < NFS Path >
    server: < NFS IP >
